#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3
bspc monitor DP-4 -d 4 5 6
bspc monitor DP-3 -d 7 8 9

bspc config border_width         2
bspc config window_gap         	10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc wmname LG3D &
$HOME/.config/polybar/launch.sh
